#: import C kivy.utils.get_color_from_hex
#: import get_color_from_hex kivy.utils.get_color_from_hex

<SplashScreen>:
	orientation: 'horizontal'
	size_hint_y: 1
	Image:
		source: "images/eagle_full.png"
		size_hint_y: .5
		size_hint_x: .5
		pos_hint: {"x": .25,"y": .4}

	MDLabel:
		text: "Eagle Schools"
		bold: True
		size_hint_y: .5
		font_size: 45
		valign: "center"
		halign: "center"